export default Object.freeze({
  id: 'zh-HK',
  name: '中文（普通话）',
  desc: 'Flashcards for Chinese',
  meta: {
    name_en: 'Chinese (Mandarin)',
    name_short: '中文',
    language_code: 'zh',
    locale_code: 'zh-CN',
    locale_code_azure: 'zh-CN',
    locale_code_deepl: 'zh',
    locale_flag: '🇨🇳',
    voice_id_azure: 'zh-CN-XiaoxiaoNeural',
  },
  key: 'emoji',
  columns: ['category', 'emoji', 'text', 'pinyin'],
  notes: [
    ['animal', '🐈', '猫', 'māo'],
    ['animal', '🐶', '狗', 'gǒu'],
    ['body', '🦶', '脚', 'jiǎo'],
    ['color', '🟢', '绿', 'lǜ'],
    ['directions', '⬇️🍂', '下', 'xià'],
    ['food', '🧊', '冰', 'bīng'],
    ['number', '7️⃣', '七', 'qī'],
    ['number', '8️⃣', '八', 'bā'],
    ['number', '9️⃣', '九', 'jiǔ'],
    ['transportation', '🚗', '汽车', 'qì chē'],
    ['verbs', '❤️😍', '爱', 'ài'],
  ],
})
