name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Publish core
        run: (cd ./core && deno publish)

      - name: Publish components
        run: (cd ./components && deno publish)

      # Depends on core
      - name: Publish adapters
        run: (cd ./adapters && deno publish)

      # Depends on core
      - name: Publish schedulers
        run: (cd ./schedulers && deno publish)

      # Depends on core
      - name: Publish utils
        run: (cd ./utils && deno publish)
